server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://rm-m5eqi52e2l5e81i1fxo.mysql.rds.aliyuncs.com:3306/little_sea?useUnicode=true&serverTimezone=GMT%2B8
    username: root
    password: Lad627886
  jpa:
    show-sql: false

#环境标识
profile: dev

publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCUd5fg+5s8USGDp/Sj3BLi3VvFx2d5SOYurEhu1LGFhhcofNBylMfoEwd1Doh9FeY0WXPcbb8Ktpsxrp8TD2J52kkzDT/LO7+3ru2i8uGID6Ikye3bOxij9S91Zs63UqjBq9QkpJ92LSbkRvIrEATxtbVn7olrLjmxapx3pPx7iwIDAQAB
privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJR3l+D7mzxRIYOn9KPcEuLdW8XHZ3lI5i6sSG7UsYWGFyh80HKUx+gTB3UOiH0V5jRZc9xtvwq2mzGunxMPYnnaSTMNP8s7v7eu7aLy4YgPoiTJ7ds7GKP1L3VmzrdSqMGr1CSkn3YtJuRG8isQBPG1tWfuiWsuObFqnHek/HuLAgMBAAECgYBWAzMqVJoKx7Xy4EsK42TNqhCQ9IUt7t3sDEOqce6mvJiODEF3IFrwSJX5awIH9bf4fBpzieE0A7bFgbUHBdK2g4wPcVUCroQkZGUsxAl/B0X2X7FBgf02q+dazro9GZQV86Q8jBrc+ug8QYV9Ab/QlwD7Df4a3/6ggOVqvcvUAQJBAMl6iE8oCGluaEpBJFpPnTDn5q+XNN95OnZhZxP+Pj0D+R6iGVblH3iszpsEnXAWcEFRa4dLdinIjr0tQYx8kasCQQC8pK5tlYW8za0xCuHIpHPD1OenEiNC7T5IH3XY+8LZVKGpm3Ej7aDjQwRz7SGyE7VoMINeVYXp1tz9cRMe7Z2hAkA7TX+1nNjs/3xe7tGea3SfIoL6CA2eAXa9xWmrrtfu6a5338qJkyMyR9sAMdmNVm1wLGD0D7gWEFxDPoDeswPFAkEAr6uUG8yQHEBUtkTx+YzbmVRc3UKQv7R6uWNCtWvOCeE8Itv0Qob5umkgbmw3YsPjvUDgNSrjZ92FMiborXaNwQJAGb1BcvFrtMYm7+oJcY+VBxyYBZdL/BmGy/n+dccxZx5O7EAderO3p+D8RzFoFxi39ROg0CJ2ISYtAVX8rSUPeA==
